# Generated by Django 6.0 on 2026-03-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="bits_id",
            field=models.CharField(
                default="TEMP_ID",
                help_text="Your official BITS Pilani ID (e.g. 2022A7PS0001G)",
                max_length=20,
                unique=True,
                verbose_name="BITS ID",
            ),
            preserve_default=False,
        ),
    ]
