# Generated by Django 6.0.3 on 2026-04-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_bits_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerrating",
            name="has_crossed_elo_floor",
            field=models.BooleanField(
                default=False, verbose_name="Has Crossed ELO Floor"
            ),
        ),
    ]
