# Generated by Django 6.0.3 on 2026-07-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playerrating_has_crossed_elo_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bits_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
