# Generated by Django 6.0.3 on 2026-03-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Game Name"
                    ),
                ),
                (
                    "is_team_based",
                    models.BooleanField(
                        default=False,
                        help_text="If True, matches involve teams instead of individual players.",
                        verbose_name="Team Based",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "scoring_unit",
                    models.CharField(
                        help_text='e.g. "points", "goals", "runs"',
                        max_length=50,
                        verbose_name="Scoring Unit",
                    ),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "minutes", "sets", "overs"',
                        max_length=50,
                        verbose_name="Duration Unit",
                    ),
                ),
                (
                    "requires_duration",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a match of this game must record duration.",
                        verbose_name="Requires Duration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "played_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Played At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "challenged_by_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Challenger ID"
                    ),
                ),
                (
                    "opponent_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Opponent ID"
                    ),
                ),
                (
                    "score",
                    models.JSONField(
                        blank=True,
                        help_text='e.g. {"challenger": 3, "opponent": 1}',
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "winner_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Winner ID"
                    ),
                ),
                (
                    "challenged_by_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenger_matches",
                        to="contenttypes.contenttype",
                        verbose_name="Challenger Type",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="arena.game",
                        verbose_name="Game",
                    ),
                ),
                (
                    "opponent_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opponent_matches",
                        to="contenttypes.contenttype",
                        verbose_name="Opponent Type",
                    ),
                ),
                (
                    "winner_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to="contenttypes.contenttype",
                        verbose_name="Winner Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-created_at"],
            },
        ),
    ]
