# Generated by Django 6.0 on 2026-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="invite_type",
            field=models.CharField(
                choices=[
                    ("invite_only", "Invite Only"),
                    ("open_challenge", "Open Challenge"),
                ],
                default="open_challenge",
                max_length=20,
                verbose_name="Invite Type",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
