# Generated by Django 6.0 on 2026-03-31 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0002_match_invite_type_alter_match_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="invited_opponent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Invited Opponent",
            ),
        ),
    ]
