# Generated by Django 6.0 on 2026-04-05 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0003_match_invited_opponent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="cancellation_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cancellation Requested By",
            ),
        ),
    ]
