# Generated by Django 6.0 on 2026-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0004_match_cancellation_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="duration_unit_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Duration Unit Number"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="scoring_unit_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Scoring Unit Number"
            ),
        ),
    ]
