# Generated by Django 6.0 on 2026-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0005_match_duration_unit_number_match_scoring_unit_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="has_standard_scoring",
            field=models.BooleanField(
                default=True,
                help_text="If False, users will be prompted to specify the target scoring amount (e.g. 21 points).",
                verbose_name="Has Standard Scoring",
            ),
        ),
    ]
