# Generated by Django 6.0 on 2026-04-05 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0006_game_has_standard_scoring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="start_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="start_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Start Requested By",
            ),
        ),
    ]
