# Generated by Django 6.0 on 2026-04-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0007_match_start_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="challenger_score_claim",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Challenger Score Claim"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="opponent_score_claim",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Opponent Score Claim"
            ),
        ),
    ]
