# Generated by Django 6.0.3 on 2026-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0008_match_challenger_score_claim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="e.g. Gymg, VK QT lawns, etc.",
                max_length=255,
                null=True,
                verbose_name="Location",
            ),
        ),
    ]
