# Generated by Django 6.0.3 on 2026-04-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0009_match_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("finalized", "Finalized"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
