name: BITS Arena Initial Test

on: [push] # This tells GitHub to trigger the pipeline on every single push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build Docker Containers
        run: docker-compose up --build

      - name: Run Django Tests
        run: docker-compose -f docker-compose.yml run web python manage.py test