name: BITS Arena Initial Test

on: [push] # This tells GitHub to trigger the pipeline on every single push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Create dummy .env file
        run: |
          touch BITS_ARENAA/.env
          echo "SECRET_KEY=dummy-key-for-testing" >> BITS_ARENAA/.env
          echo "DEBUG=True" >> BITS_ARENAA/.env
          echo "POSTGRES_DB=test_db" >> BITS_ARENAA/.env
          echo "POSTGRES_USER=test_user" >> BITS_ARENAA/.env
          echo "POSTGRES_PASSWORD=test_password" >> BITS_ARENAA/.env
          echo "POSTGRES_HOST=test_host" >> BITS_ARENAA/.env
          echo "POSTGRES_PORT=5432" >> .env
      
      - name: Build Docker Containers
        run: docker compose -f BITS_ARENAA/docker-compose.yml build

      - name: Run Django Tests
        run: docker compose -f BITS_ARENAA/docker-compose.yml run web python manage.py test